In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
from scipy.stats import sem
import numpy as np

In [13]:
# fake up some data
spread = np.random.rand(50) * 100
center = np.ones(25) * 50
flier_high = np.random.rand(10) * 100 + 100
flier_low = np.random.rand(10) * -100
data = np.concatenate((spread, center, flier_high, flier_low))

# fake up some more data
#spread = np.random.rand(50) * 100
#center = np.ones(25) * 40
#flier_high = np.random.rand(10) * 100 + 100
#flier_low = np.random.rand(10) * -100
d2 = np.concatenate((spread, center, flier_high, flier_low))
# Making a 2-D array only works if all the columns are the
# same length.  If they are not, then use a list instead.
# This is actually more efficient because boxplot converts
# a 2-D array into a list of vectors internally anyway.
data = [data, d2, d2[::2]]
print(data)

# Multiple box plots on one Axes
#fig, ax = plt.subplots()
#ax.boxplot(data)

#plt.show()

[array([ 70.702699  ,  13.66094733,  15.66140823,  67.60953254,
        43.99898388,  41.85047035,  18.04986443,  79.29241928,
         7.04433844,  39.38493537,  73.4429602 ,  65.8467993 ,
        93.73426803,  38.38360588,  47.08010047,  72.45243953,
         9.60631007,  20.91291852,  78.23738809,  16.60597074,
        16.28040224,   4.90949297,  32.67302374,  41.82690442,
        89.91252112,  71.53794178,  22.27496079,  77.92958264,
        13.54787328,  78.56756586,  67.27667742,  63.47722181,
        10.0369268 ,  48.33543294,  52.6582504 ,  30.57330905,
        40.64656622,  29.95450123,  23.64758764,  29.67768228,
        56.91482886,  21.72317744,  22.82446238,  66.6376703 ,
        86.19848854,  91.82741357,  87.21671638,  51.31833484,
        72.25454225,  76.53955634,  50.        ,  50.        ,
        50.        ,  50.        ,  50.        ,  50.        ,
        50.        ,  50.        ,  50.        ,  50.        ,
        50.        ,  50.        ,  50.        ,  50. 

In [3]:
spread

array([51.09198647, 15.11761023, 89.0335748 , 86.0517245 ,  9.25005497,
       31.84631032,  4.19185931,  0.20935423, 11.32481994, 58.72330667,
       45.56646304, 65.21372595, 76.66581411, 70.81582953, 63.35370348,
       31.77139388, 87.23416678, 33.90442785, 59.62807384, 44.92940725,
       69.4317756 , 40.39352086, 65.99306604, 74.93280695, 55.5071795 ,
       57.64277794, 68.46187826, 68.77431427, 49.50400279,  7.2449593 ,
       26.35026729, 12.33702691, 61.14723386,  9.58389311, 80.82345817,
       45.93595947, 72.13747704, 57.92439436, 36.58206685, 11.11629629,
       99.07780671,  5.55370048, 39.9878821 , 49.76212781, 13.03560461,
       16.71301027, 11.39009147, 34.03993626, 42.36873227, 78.21214549])

In [4]:
center

array([50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50.,
       50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50.])

In [6]:
flier_high

array([121.23642515, 174.62664992, 177.59098766, 150.61803522,
       108.099305  , 124.10062516, 151.20365372, 172.48915897,
       101.13265578, 119.52145482])

In [9]:
flier_low

array([-43.35027648, -97.17899838, -51.54490768, -81.53505448,
       -20.46612529, -55.6202514 , -86.1365527 ,  -3.56860726,
       -73.27510841, -73.15048917])

In [8]:
data

array([ 58.65320832,  81.65027411,  94.40222824,  80.90130149,
        77.89183401,  55.89258326,  71.84152019,  11.37367679,
        99.52324228,  58.91213415,  21.21513599,  80.13429578,
        40.73915386,  97.29978401,  38.8598681 ,  27.45321656,
        32.15426843,  79.82702995,  69.23175706,  64.69693683,
        82.99234588,  68.66572513,  76.34376372,  87.85349536,
        85.49507212,  43.49317727,  13.43012763,   3.64728825,
        88.15032821,  71.52527102,  78.49278566,  72.10654362,
        95.95154076,  39.80812955,  96.00703505,  74.66210011,
        84.15790271,  40.17620783,  49.81274839,  46.03331134,
        99.93908949,  50.66972182,   2.00744846,  42.09347842,
         9.95484012,  94.49280294,  75.89547122,  77.36353592,
        24.8277027 ,  95.80324707,  50.        ,  50.        ,
        50.        ,  50.        ,  50.        ,  50.        ,
        50.        ,  50.        ,  50.        ,  50.        ,
        50.        ,  50.        ,  50.        ,  50.  